const PRODUCTS = [
  {
    id: 'boss-bagels',
    name: 'Boss Bagels',
    shortName: 'Pack of 4',
    description:
      'Chunky, chewy gluten-free sourdough bagels, glazed with golden syrup and finished with chia seeds.',
    weeklyPrice: 449,
    serves: 'Gluten free sourdough bagels',
    bestFor: 'Toasting, filling, freezing, and weekday breakfasts',
    includes: ['Pack of 4 bagels', 'Chia seed finish', 'Vegan friendly', 'Free from gluten, dairy, egg, nuts and soya'],
    accent: '#c08a2d',
    badge: 'Bestseller',
    image_url: '/assets/Boss_Bagels_Stack.webp',
    gallery_images: ['/assets/Boss_Bagels_Stack.webp', '/assets/Boss_Bagels_Detail.webp'],
    category: 'Bagels',
    sourceUrl: 'https://www.mygfbakery.com/products/gf-sourdough-boss-bagels',
  },
  {
    id: 'super-sourdough',
    name: 'Super Sourdough',
    shortName: 'Gluten free sourdough loaf',
    description:
      'The bakery’s most popular loaf: a bold, tangy gluten-free sourdough with a firm crisp crust.',
    weeklyPrice: 475,
    serves: '1 loaf',
    bestFor: 'Toast, butter, savoury toppings, and freezer stock',
    includes: ['Slow-fermented sourdough', 'Crisp crust', 'Available sliced or unsliced', 'Suitable for freezing'],
    accent: '#835832',
    badge: 'Customer favourite',
    image_url: '/assets/Super_Sourdough-06.webp',
    gallery_images: ['/assets/Super_Sourdough-06.webp'],
    category: 'Loaves',
    sourceUrl: 'https://www.mygfbakery.com/products/super-sourdough-gf-loaf',
  },
  {
    id: 'totally-seeded',
    name: 'Totally Seeded',
    shortName: 'Seeded sourdough loaf',
    description:
      'A seeded gluten-free sourdough loaf with a hearty crumb and proper bakery flavour.',
    weeklyPrice: 475,
    serves: '1 loaf',
    bestFor: 'Everyday bread with extra texture',
    includes: ['Seeded loaf', 'Teff sourdough style', 'Vegan friendly', 'Free from major allergens'],
    accent: '#6d7e42',
    badge: '5.0 rated',
    image_url: '/assets/TotallySeededWhole.webp',
    gallery_images: ['/assets/TotallySeededWhole.webp', '/assets/TotallySeededSliced.webp'],
    category: 'Loaves',
    sourceUrl: 'https://www.mygfbakery.com/products/totally-seeded',
  },
  {
    id: 'tinned-sandwich-loaf',
    name: 'Tinned Sandwich Loaf',
    shortName: 'Sliced everyday loaf',
    description:
      'A fluffy structured gluten-free sandwich loaf, sliced and made for toast, sandwiches, and freezing.',
    weeklyPrice: 569,
    serves: '1 sliced loaf',
    bestFor: 'Sandwiches, toast, and lunch boxes',
    includes: ['Sliced loaf', 'Structured tin shape', 'Vegan friendly', 'No added sugar'],
    accent: '#d2a148',
    badge: 'Everyday staple',
    image_url: '/assets/Tinned_Loaf-01.webp',
    gallery_images: ['/assets/Tinned_Loaf-01.webp', '/assets/Tinned_Loaf-09.webp'],
    category: 'Loaves',
    sourceUrl: 'https://www.mygfbakery.com/products/sourdough-sandwich-loaf',
  },
  {
    id: 'classic-bagels',
    name: 'Classic Bagels',
    shortName: 'Pack of 4',
    description:
      'Award-winning plain gluten-free sourdough bagels with a soft, chewy texture and balanced flavour.',
    weeklyPrice: 449,
    serves: 'Gluten free sourdough bagels',
    bestFor: 'Sweet or savoury toppings',
    includes: ['Pack of 4 bagels', '2024 Free From Award Gold Winner', 'Sourdough starter', 'Vegan friendly'],
    accent: '#e0a13c',
    badge: 'Award-winning',
    image_url: '/assets/Classic_Bagels.webp',
    gallery_images: ['/assets/Classic_Bagels.webp', '/assets/Bagels_Multipack-01.webp'],
    category: 'Bagels',
    sourceUrl: 'https://www.mygfbakery.com/products/classic-gf-bagels',
  },
  {
    id: 'nigella-garlic-bagels',
    name: 'Nigella Seed and Garlic Bagels',
    shortName: 'Pack of 5',
    description:
      'A savoury gluten-free sourdough bagel with nigella seed and garlic for a bigger, bolder bite.',
    weeklyPrice: 565,
    serves: '5 bagels',
    bestFor: 'Savoury breakfasts and lunch fillings',
    includes: ['Pack of 5 bagels', 'Nigella seeds', 'Garlic finish', 'Vegan friendly'],
    accent: '#4f6f57',
    badge: 'Savoury favourite',
    image_url: '/assets/GAarlic_Nigella-15.webp',
    gallery_images: ['/assets/GAarlic_Nigella-15.webp', '/assets/GAarlic_Nigella-17.webp'],
    category: 'Bagels',
    sourceUrl: 'https://www.mygfbakery.com/products/nigella-seed-and-garlic-bagels',
  },
  {
    id: 'bagel-selection-box',
    name: 'Bagel Selection Box',
    shortName: 'Mixed bagel box',
    description:
      'A mixed box of gluten-free sourdough bagels, ideal for trying different flavours and stocking the freezer.',
    weeklyPrice: 935,
    serves: 'Mixed bagels',
    bestFor: 'Families, sharing, and discovering favourites',
    includes: ['Boss Bagels', 'Classic Bagels', 'Seasonal bagel styles', 'Freezer friendly'],
    accent: '#b76832',
    badge: 'Mixed box',
    image_url: '/assets/Bagels_Multipack-01.webp',
    gallery_images: ['/assets/Bagels_Multipack-01.webp', '/assets/Classic_Bagels.webp', '/assets/Boss_Bagels_Stack.webp'],
    category: 'Boxes & Bundles',
    sourceUrl: 'https://www.mygfbakery.com/products/bagel-selection-box-gluten-free-sourdough-bagels-mixed-box',
  },
  {
    id: 'loaves-mixed-box',
    name: 'Mixed Bread Box',
    shortName: '4 gluten-free loaves',
    description:
      'A curated selection of four gluten-free sourdough loaves: Super Sourdough, Totes Oats, Totally Seeded and Tinned Sandwich Loaf.',
    weeklyPrice: 1899,
    serves: '4 loaves',
    bestFor: 'Weekly essentials and finding your favourite loaf',
    includes: ['Super Sourdough', 'Totes Oats', 'Totally Seeded', 'Tinned Sandwich Loaf'],
    accent: '#7d5f3a',
    badge: 'Better value',
    image_url: '/assets/Bread_Multipack-1.webp',
    gallery_images: ['/assets/Bread_Multipack-1.webp', '/assets/Super_Sourdough-06.webp', '/assets/TotallySeededWhole.webp'],
    category: 'Boxes & Bundles',
    sourceUrl: 'https://www.mygfbakery.com/products/mixed-box-of-3-loaves-gluten-free-sourdough-loaves',
  },
  {
    id: 'baguette',
    name: 'Brilliant Baguette',
    shortName: 'Gluten free sourdough baguette',
    description:
      'A crusty gluten-free baguette for dinner tables, sandwiches, garlic bread, and tearing warm from the oven.',
    weeklyPrice: 289,
    serves: '1 baguette',
    bestFor: 'Dinner, dipping, and quick lunches',
    includes: ['Crusty baguette', 'Vegan friendly', 'Freezer friendly', 'Fresh to order'],
    accent: '#b67b30',
    badge: 'Fresh from the oven',
    image_url: '/assets/Baguette-5.jpg',
    gallery_images: ['/assets/Baguette-5.jpg', '/assets/Baguette-2.jpg', '/assets/Baguette-3.jpg'],
    category: 'Loaves',
    sourceUrl: 'https://www.mygfbakery.com/collections/loaves-baguettes',
  },
  {
    id: 'build-a-box',
    name: 'Build-a-Box',
    shortName: 'Mix. Match. Munch.',
    description:
      'A flexible bundle inspired by My Gluten Free Bakery’s build-a-box range. Mix loaves and bagels to stock up and save.',
    weeklyPrice: 1599,
    serves: 'Bundle',
    bestFor: 'Families and weekly freezer stock',
    includes: ['Choose bagels', 'Choose loaves', 'Bundle value', 'Free local delivery over £35'],
    accent: '#2f7465',
    badge: 'Stock up & save',
    image_url: '/assets/Breakfast-Edit-Yumbles.webp',
    gallery_images: ['/assets/Breakfast-Edit-Yumbles.webp', '/assets/Bread_Multipack-1.webp', '/assets/Bagels_Multipack-01.webp'],
    category: 'Boxes & Bundles',
    sourceUrl: 'https://www.mygfbakery.com/collections/bundles',
  },
];

const DELIVERY_DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];

const BUILD_YOUR_BOX_ITEMS = PRODUCTS.map((product) => ({
  id: product.id,
  name: product.name,
  type: product.category,
}));

function getProductById(id) {
  return PRODUCTS.find((product) => product.id === id) || null;
}

function formatPrice(pence) {
  return `GBP ${(pence / 100).toFixed(2)}`;
}

module.exports = { PRODUCTS, DELIVERY_DAYS, BUILD_YOUR_BOX_ITEMS, getProductById, formatPrice };
